---
stages:
  - checks
  - test
  - push

variables:
  GITHUB_USER: lotusnoir


##################################################
# PREFLIGHT
##################################################
yamllint:
  stage: checks
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

ansible-lint:
  stage: checks
  image: lotusnoir/ansible_play
  script:
    - ansible-lint .

######################################################
# RUN ROLE ON DIFFERENTS OS
######################################################
debian11:
  stage: test
  needs:
    - yamllint
    - ansible-lint
  image:
    name: lotusnoir/ansible_molecule_test_images:debian11
    entrypoint: [""]
  before_script:
    - ansible --version
  script:
    - ansible-galaxy install -r requirements.yml
    - cd ..
    - ansible-playbook ansible-apps_adminer/playbook.yml


######################################################
# RUN MOLECULE FOR FULL TEST SCENARIO
######################################################
molecule:
  stage: test
  needs:
    - debian11
  image: lotusnoir/molecule_play
  before_script:
    - molecule --version
  script:
    - molecule test


##################################################
# PUSH CODE WHEN ALL TEST OK
##################################################
push_src_on_github:
  stage: push
  image: alpine:latest
  needs:
    - molecule
  before_script:
    - apk add git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GITHUB_USER_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tUser ansible\n\tStrictHostKeyChecking no\n\tForwardAgent yes\n\n" > ~/.ssh/config
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global user.name "${GITHUB_USER}"
    - git config --global init.defaultBranch main
  script:
    - git clone git@github.com:${GITHUB_USER}/docker-molecule_debian11.git /tmp/docker-molecule_debian11
    - rm -rf .git
    - cp -r . /tmp/docker-molecule_debian11/
    - cd /tmp/docker-molecule_debian11
    - git add -A
    - git commit -m "fix" || echo "No changes, nothing to commit!"
    - git push
