---
- name: "Check for adminer files"
  stat:
    path: "{{ adminer_install_dir }}/index.php"
  changed_when: false
  register: adminer_install

- name: "Get current version"
  shell: |
    set -o pipefail
    grep @version {{ adminer_install_dir }}/index.php | awk '{print $NF}'
  args:
    executable: /bin/bash
  changed_when: false
  register: adminer_install_version
  when: adminer_install.stat.exists

- name: Installation process
  when: (not adminer_install.stat.exists) or (adminer_install_version is defined and adminer_version not in adminer_install_version.stdout)
  block:
    - name: "Install requierements"
      package:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - "{{ adminer_packages }}"

    - name: "Ensure install dir exist"
      file:
        path: '{{ adminer_install_dir }}'
        state: directory
        owner: '{{ adminer_owner }}'
        group: '{{ adminer_group }}'
        mode: 0755

    - name: "Download adminer files"
      get_url:
        url: '{{ adminer_src_url }}'
        dest: '{{ adminer_install_dir }}/index.php'
        owner: '{{ adminer_owner }}'
        group: '{{ adminer_group }}'
        mode: 0766

- name: "Download Adminer theme"
  get_url:
    url: "{{ adminer_theme_root_url }}/{{ adminer_theme }}/adminer.css"
    dest: "{{ adminer_install_dir }}"
    owner: '{{ adminer_owner }}'
    group: '{{ adminer_group }}'
    force: true
    mode: 0644
    timeout: 60
  when: adminer_theme|length>0
